### ISSUE TITLE
Kitty Image Protocol Support

### ISSUE THREAD

**Issue by wez** [wezterm/wezterm#986]
This issue is tracking the status of supporting Kitty's image protocol.

Spec at: https://sw.kovidgoyal.net/kitty/graphics-protocol/

* [x] termwiz: parse APC escapes
* [x] termwiz: parse baseline Kitty Image protocol APC escapes
* [x] term: basic placement implementation on top of existing iTerm2/sixel image data model
* [x] term: add placement data model to support full range of kitty placement options
* [x] wezterm-gui: teach renderer to allocate quads for new placement model
* [x] termwiz: parse animation/composition kitty image protocol sequences
* [x] term: apply animation to model
* [ ] handle [animation control](https://sw.kovidgoyal.net/kitty/graphics-protocol/#controlling-animations)
* [ ] termwiz: support data transmission via shared memory on unix
* [ ] termwiz: support data transmission via shared memory on Windows
* [ ] placeholder support, which might enable support to function in tmux
  (Original feature author @sergei-grechanik did a possible impl at https://github.com/sergei-grechanik/wezterm/commit/d3df8e5e608df7bb9261f95e8a8f01b06a7a32b4, to be tested and re-produced as a properly focused PR)
  Potential PR: https://github.com/wezterm/wezterm/pull/7924

## Using it:

Enable the protocol by setting `enable_kitty_graphics=true` in your config.

## Known conformance issues

* ~~The spec models image placements independently from the terminal cells, but wezterm maps them to terminal cells at placement time.  As a result, over-writing cells with text can poke holes in wezterm which may not appear in kitty~~.

**Comment by kovidgoyal** [comment]
I am happy to see this, please don't hesitate to ping me if you have any questions.

**Comment by wez** [comment]
> I am happy to see this, please don't hesitate to ping me if you have any questions.

Great to hear!  Do you have a set of tests or similar that could be made to run against wezterm to sanity check conformance?
The surface area of the spec is quite large and I'm sure I'm going to overlook something.  My game plan is try running @dankamongmen's notcurses demo when there's enough of an implementation working and see if anything looks egregiously bad.

**Comment by kovidgoyal** [comment]
I do have unit tests in kitty itself, for individual bits of functionality from the protocol, but I doubt they can be easily lifted for another terminal emulator. If you wish to have a look, please see kitty_tests/graphics.py 

I would actually be happy to collaborate to make those (and other) tests defined in a terminal independent fashion so anyone implementing the protocol could use them. Perhaps a simple txt or json based format that specifies the input as escape codes and the output as a set of image placement data or similar.

**Comment by dankamongmen** [comment]
> > I am happy to see this, please don't hesitate to ping me if you have any questions.
> 
> Great to hear! Do you have a set of tests or similar that could be made to run against wezterm to sanity check conformance?
> The surface area of the spec is quite large and I'm sure I'm going to overlook something. My game plan is try running @dankamongmen's notcurses demo when there's enough of an implementation working and see if anything looks egregiously bad.

first off, i enthusiastically support this move. the kitty protocol is (at least for my purposes) a tremendous improvement upon both sixel and iterm. it simplifies things (no more requirement that one draw in terms of 6 rows, sane deletion behavior), improves performance in several areas (fast moves, fast changes to drawn images), and makes certain things possible that otherwise are not (text drawn atop bitmaps without killing entire cells). relative to iterm2, it's much more flexible and powerful. at the same time, it *currently* shows worse local performance in Notcurses due to (a) greater bandwidth demands than sixel and (b) time spent in zlib. i expect to be able to hide the latter in most applications via threading. it would be possible to reduce the local bandwidth via using the filesystem as a side channel to load images, but i have not yet embraced this, and **might** never do so (but might, who knows).

right now Notcurses selects the Kitty protocol strictly based on heuristics, as opposed to doing the recommended query. I intend to add support for the latter (and really ought have by now), but hadn't bothered since no one else had implemented it (and also because said query frustratingly doesn't let you determine the version of the kitty protocol supported--as you note, it's a large protocol). you can ensure kitty graphics are being used by running `notcurses-info`:

![2021-07-29-005228_1083x620_scrot](https://user-images.githubusercontent.com/143473/127433817-d3a24246-01ff-422c-9265-b2664abc0a91.png)

where it says "rgba pixel animation support", you want that. wezterm currently says "sixel graphics" or "iterm graphics", i forget which one. if it says "rgba ....", you're driving kitty graphics. i'll try to add this query soon.

Notcurses uses a pretty wide subset of the protocol, and indeed [motivated/proposed](https://github.com/kovidgoyal/kitty/issues/3809) some of it. Among the elements it exercises are:

* image loading via 32-bit RGBA without display
* display of loaded images
* movement of loaded images via position commands
* deletion of loaded images specified by id
* deletion of all images present
* scrolling of images
* inhibition of responses via `q=2`
* non-scrolling of images via `C=1`
* images in both the regular screen and alternative screen
* fast cell-sized wipes via the animation protocol + RGBA load
* fast cell-sized restores via the animation protocol + reflection (composition)
* display of images larger than the terminal width (kitty cuts off excess material on the right), but only due to an existing bug

i **do not** currently exercise: sideloading images via the filesystem, managed animations, scaling, or z-indices other than 0, though i expect to start using the last Really Soon Now.

`notcurses-tester` and `ncplayer -bpixel` will also effectively test portions of your implementation.

if you have any questions, don't hesitate to ask me; i reckon i know more about the kitty graphics protocol than anyone living save @kovidgoyal himself. happy hacking!

**Comment by dankamongmen** [comment]
> if you have any questions, don't hesitate to ask me; i reckon i know more about the kitty graphics protocol than anyone living save @kovidgoyal himself. happy hacking!

oh and let me add that i make use of kitty's honoring of transparency values in RGBA (at at least a bimodal level), just as I do in iterm, and using unspecified pixels in sixel when P2=1 in sixel.

**Comment by kovidgoyal** [comment]
@dankamongmen regarding using heuristics for detection, because you dont have a version. You shouldnt need a version. You can create a dummy image and try to perform every operation you want on it and see if it succeeds, i.e. the terminal does not respond with an error. Thus you can know exactly what the terminal you are running in supports. 

And of course as am sure you already know, if you really want a version us XTVERSION or XTGETTCAP

**Comment by dankamongmen** [comment]
> And of course as am sure you already know, if you really want a version us XTVERSION or XTGETTCAP

this is exactly what i'm doing, see https://github.com/dankamongmen/notcurses/blob/master/src/lib/termdesc.c#L501-L527

> @dankamongmen regarding using heuristics for detection, because you dont have a version. You shouldnt need a version. You can create a dummy image and try to perform every operation you want on it and see if it succeeds, i.e. the terminal does not respond with an error. Thus you can know exactly what the terminal you are running in supports.

yep, i could do that. what i've got now works for me pretty well, though.

and let it be known in all lands the sun touches: i wholeheartedly affirm the use of the Kitty graphics protocol over others. indeed, i sat down a few weeks ago to [describe my ideal terminal graphics protocol](https://nick-black.com/dankwiki/index.php?title=Spriteful_TErminal_GrAphics_Protocol), and ended up with something very similar to Kitty's.

i will be adding support for coarse kitty graphics support very shortly, probably tonight, in https://github.com/dankamongmen/notcurses/issues/1998.

**Comment by stevenxxiu** [comment]
@wez I'm trying to use *Broot* in *Wezterm* and opened an issue there. Mind taking a look at some problems in https://github.com/Canop/broot/issues/473#issuecomment-1005995882 with the protocol support?

> Kitty's spec specifies that *"The image will be scaled (enlarged/shrunk) as needed to fit the specified area"* and Wezterm doesn't seem to respect that.
> 
> I've also another problem: the only way to correctly detect the support without having problems on some terminals seems to be to read an env var and there's no guarantee wezterm sets it in an adequate way.

**Comment by Canop** [comment]
All is fine now, Broot displays high resolution images in WezTerm:

![image](https://user-images.githubusercontent.com/617006/148505437-fcb73cc3-f6da-44c0-8e57-c1bbd1068f60.png)

**Comment by AnonymouX47** [comment]
Hello!

First of all, great work here and I do recognize that there's no claim that the terminal fully supports the kitty graphics protocol yet.

I'm currently working on a project that uses this protocol to display images (See https://github.com/AnonymouX47/term-image/issues/40).
So far, everything I've implemented is working fine on Kitty.. and then I decided to try it out on other terminal emulators that were mentioned to support the protocol, Werzterm being the first.

From my short try with Werzterm (nightly build, downloaded few hours before sending this message), I've encountered a number of crippling (for my use case) inconsistencies with the protocol's specifications (or behaviour in kitty). Here are a few:


### 1. Every image transmited without an ID is replaced by the next image also without an ID.

According to the specification:
> You can either simultaneously transmit and display an image using the action a=T, **or** first transmit the image with a id, such as i=10 and then display it with a=p,i=10 which will display the previously transmitted image at the current cursor position.

*emphasis on the "or"*
From my understanding, this means `a=T` without an ID should simply place the image without attaching it to an ID... which doesn't seem like what Wezterm does.

Trying `a=T` on kitty displayed as many images as I tried (a lot) without deleting anyone... but that was not the case with Wezterm.


### 2. Control codes `c` and `r` don't exactly work as specified.

If `c` and `r` are in relative proportion to the image, it'll scale the image... else it crops the image. (See the images below)

![image](https://user-images.githubusercontent.com/61663146/167337100-e0b656dd-3e26-4b69-b42b-d37694f92d3a.png)
Scaled

![image](https://user-images.githubusercontent.com/61663146/167337261-860e1759-ea69-40fa-b3a5-9b535f2b033f.png)
Cropped (and the scale is even way off)

![image](https://user-images.githubusercontent.com/61663146/167337299-796b410e-b5bd-4444-b6b6-7db78a871714.png)
Cropped


### 3. Cursor advancement

According to the specs:
> After placing an image on the screen the cursor must be moved to the right by the number of cols in the image placement rectangle and down by the number of rows in the image placement rectangle.

Trying this without `C=1` (which Wezterm doesn't support yet) and without the cursor reaching either edge of the window:

- On kitty, the cursor ends up on on the cell to the right of the bottom-leftmost cell occupied by the image.
- On Wezterm, the cursor ends up on the first cell of the line immediately below that bottommost line occupied by the image.

*Can't readily provide images now but I'm pretty sure those were the results*

* * *
Please, keep in mind that inconsistency in interpretations and implementations of protocols is one of the major reasons we're where we are with terminal emulators today.

Thanks for your audience and I do hope you look into these and more... Keep up the great work.

**Comment by AnonymouX47** [comment]
By the way, here are the results of `c` and `r` with kitty:

![image](https://user-images.githubusercontent.com/61663146/167341222-69af90ce-d034-42aa-be7a-661d948dd54e.png)

![image](https://user-images.githubusercontent.com/61663146/167341239-c3944bdd-ffeb-46f8-af6d-d778bb726a9c.png)

![image](https://user-images.githubusercontent.com/61663146/167341248-1e619d63-9746-4240-ab24-46cfcbc4b247.png)

All properly scaled.

**Comment by AnonymouX47** [comment]
Oh! I totally understand that, I was only expecting some form of acknowledgement (of the comment).

It's not urgent for me as I personally don't use Wezterm, I was only testing out my project in different terminal emulators and decided to report bugs/issues I found (just like https://github.com/kovidgoyal/kitty/issues/5081).

Thanks for your response.

**Comment by dholth** [comment]
Do I remember correctly that wezterm used to have a "cat image to screen" utility? Where's a good one?

**Comment by AnonymouX47** [comment]
The default tool is the `imgcat` subcommand. As described [in thw docs](https://wezfurlong.org/wezterm/imgcat.html):

> To render an image inline in your terminal:
>
> ```sh
> $ wezterm imgcat /path/to/image.png
> ```

Also, you can use [term-image](https://github.com/AnonymouX47/term-image) which provides an interactive user interface for browsing/viewing images... still under developmenr though.

Disclosure: I might be biased about the latter :) but feel free to judge for yourself.

There are a few other tools out there that also perform similar tasks e.g [timg](https://github.com/hzeller/timg).

**Comment by bew** [comment]
The latest release of Kitty added an interesting feature that allow displaying images without explicit support from a program, using unicode chars, diacritics and fg color to select and position an image.
Refs:
- https://sw.kovidgoyal.net/kitty/graphics-protocol/#unicode-placeholders
- https://github.com/kovidgoyal/kitty/pull/5664

**Comment by AnonymouX47** [comment]
A wezterm fork (by the author of the feature) that implements support for the feature: https://github.com/sergei-grechanik/wezterm/tree/unicode-placeholders

**Comment by AnonymouX47** [comment]
On another note... I recently tested out the kitty graphics protocol support to see how far it's come since https://github.com/wez/wezterm/issues/986#issuecomment-1120622597.

`w`, `h` and a couple other control data work fine now but `C=1` (do not move cursor) isn't implemented yet. I feel this technically shouldn't be far fetched since `doNotMoveCursor` has been implemented for the iterm protocol a long time ago.

It'll be really useful to have this implemented as it's literally the only thing standing in the way of a project I'm working on... If I did write Rust, I'd sincerely have opened a PR a long time ago.

Thanks.

**Comment by AndydeCleyre** [comment]
Assuming that adding support for Kitty's unicode placeholder model means Wezterm + tmux can support the Kitty image protocol, can we get a todo-checkbox for it up top here?

**Comment by constantitus** [comment]
I'm trying to find a good way to display images in neovim, but most plugins use the kitty protocol, which doesn't seem to work as intended on wezterm.
What would cause this discrepancy between kitty and wezterm ?

https://github.com/wez/wezterm/assets/118078873/0412c0be-ae5f-44fb-9d9d-122ac94b98c9

**Comment by dhruvkb** [comment]
There is a bug where sending using an image in two places only renders it once.

When I first send the RGBA data with `a=t`, then display the image separately with `a=p` in two places, the image is moved instead of adding a new extra placement. This works correctly in Kitty (left), whereas the icons for `.pre-commit-config.yaml` and `prettier.config.mjs` are missing in WezTerm (right).

<img width="1728" alt="Screenshot 2024-09-15 at 5 44 46 AM" src="https://github.com/user-attachments/assets/06c45523-b50e-4d3d-aee1-0e736d6e3b71">

**Comment by panki27** [comment]
Transmission using shm should be possible according to https://github.com/wezterm/wezterm/pull/1810 - which conflicts with the summary up above. 🤔 

~~Could somebody please clarify for me if this is supposed to work in the latest nightly out of the box, or do I need to set a flag at compile time or similar? I can not get graphics to work using shm (commented in the linked PR).~~

Edit: Ahh I just realized that's most likely because I'm using WSL - WezTerm is running as a Windows application and probably fails to read from the `/dev/shm` location inside the WSL :(
Edit 2: Confirmed, I installed wezterm inside WSL and that's working perfectly fine.

**Comment by unxed** [comment]
For some reason, kitty graphics protocol is [not working](https://github.com/elfmz/far2l/issues/3201) in [far2l](https://github.com/elfmz/far2l) (`F11`, `i`):

<img width="1558" height="1196" alt="Image" src="https://github.com/user-attachments/assets/4af693d4-d54d-4bb7-8c06-2b212b328bc7" />


At the same time, it works in kitty and Konsole quite well:

<img width="1600" height="1316" alt="Image" src="https://github.com/user-attachments/assets/51529db4-23d9-494d-b9c6-472971d7bba7" />

Perhaps WezTerm is responding to a request for protocol support incorrectly, or not responding at all? (upd: [fix](https://github.com/elfmz/far2l/issues/3201#issuecomment-3737558122) on far2l side)

**Comment by unxed** [comment]
While fixing kitty images protocol in far2l in WezTerm, found one more difference between WezTerm and kitty behavior:
https://github.com/elfmz/far2l/issues/3201#issuecomment-3794618995

**Comment by bew** [comment]
FYI I think I've labelled all active issues/PRs with `T: term/graphics`, they can all be seen [here](https://github.com/wezterm/wezterm/issues?q=sort%3Aupdated-desc%20state%3Aopen%20kitty%20label%3A%22T%3A%20term%2Fgraphics%22)
